### PR TITLE
Make CSCS retrieve more descriptive

### PR DESCRIPTION
**Pull request by minottic**
should close: #175

### CODE REVIEW

**Comment by minottic** [comment]
since we can explain in more detail what each option does, we could change the `Get download URLs` to simply `Download`.

**Review by stephan271 — APPROVED** [review]

**Comment by pozsa** [comment]
something like the below?

```
        {
            "option": "to PSI",
            "tooltip": "Copy the data to the PSI storage buffer. After that, you need to copy it from there to any destination using the datasetRetriever command or using rsync from pb-retrieve.psi.ch"
        },
        {
            "option": "download URLs",
            "tooltip": "Get an email with temporary links to download the data. Clicking on the links will start the download."
        },
        {
            "option": "to PSI-RA",
            "location": "/gpfs/workfs/p18/p18525/retrieve",
            "tooltip": "Copy the data directly to the PSI RA cluster destination folder at /das/work/${groupname:0:3}/${groupname}/retrieve/${sourceFolder}/"
        }
```

Which one is the default option? Currently, none is marked, but there is actually one in the background.
I know because I could trigger a job without selecting any of the options.

**Comment by minottic** [comment]
> Which one is the default option? Currently, none is marked, but there is actually one in the background.
I know because I could trigger a job without selecting any of the options.

the default should be the first one in the list

**Comment by minottic** [comment]
do we want CSCS as the default one?

**Comment by stephan271** [comment]
Good question: if we however apply the "principle of minimum surprise" we should keep the PSI case as the default (at least for now)

**Comment by minottic** [comment]
the dialog looks like this:
image

so having the "to " prefix might be a little redundant, and also it has implications on the `job.jobParams.option` value which I think is used in nodered to distinguish the retrieve types (as the value would be "to PSI" as opposed to "PSI"). 
So, I would suggest to keep them as they are, i.e. simply PSI and PSI-RA. I am happy to change the CSCS one, as that is not known to the user. As before, @pozsa , this will require a change in nodered as well I think

**Comment by pozsa** [comment]
can we make it `selected` in the UI? so there is no empty option, but the user sees which one is happening?

**Comment by pozsa** [comment]
> the dialog looks like this: image
> 
> so having the "to " prefix might be a little redundant, and also it has implications on the `job.jobParams.option` value which I think is used in nodered to distinguish the retrieve types (as the value would be "to PSI" as opposed to "PSI"). So, I would suggest to keep them as they are, i.e. simply PSI and PSI-RA. I am happy to change the CSCS one, as that is not known to the user. As before, @pozsa , this will require a change in nodered as well I think

well.. I think it's not optional to select a destination. They are forced to select a destination.
You are right about the changes in nodered though.

how about this?
- instead of "Really retrieve?" it should say "Retrieve to?"
- delete "Optionally select destination"
- when this form/popup opens the default option is selected on the UI so the user knows which one happens when they click "ok"
- I change nodered from `CSCS` to `download URLs`

or have an actual `value` with the `option` so the user doesn't see the actual value we use to route our logic on, but only sees a display

**Comment by stephan271** [comment]
I like this proposal

**Comment by minottic** [comment]
that's a good idea. My comment was indeed only to avoid the "to " but, I agree on changing the rest!

**Comment by minottic** [comment]
@pozsa your suggestion has been implemented. You can check it out on discovery-development.psi.ch (you might need to clear the cache first)

**Comment by pozsa** [comment]
> @pozsa your suggestion has been implemented. You can check it out on discovery-development.psi.ch (you might need to clear the cache first)

Hmm, seeing it now.. what do you think if we just call it `URLs` instead of `download URLs`?
and the help text:
`Get an email with temporary URLs to download the data. Clicking on the URLs will start the download`?

**Comment by minottic** [comment]
@pozsa new wording should be there

**Review by pozsa — APPROVED** [review]

**Pull request merged**
