### PR TITLE
Prevent finished CSCS jobs to send queue updates

### PR DESCRIPTION
**Pull request by minottic**
should close: #123

### CODE REVIEW

**Comment by pozsa** [comment]
Wouldn't it be easier to extend the existing if statement with `...jobParams.option != "CSCS"` bit?

**Comment by minottic** [comment]
that was my first approach indeed. I am just not sure if `jobParams` is there for all jobs and if it has the option field every time, thus the more verbose check

**Comment by pozsa** [comment]
Okay, looks good to me.

**Comment by minottic** [comment]
should be superseded by https://github.com/paulscherrerinstitute/scicat-ci/tree/disable_posting_success

**Pull request closed without merging**
